[package]
name = "MathPotato"
version = "0.0.14"
edition = "2024"

[dependencies]
uuid = { version = "1.17.0", features = ["v4"] }
derive_more = { version = "2", features = ["full"] }
anyhow = { version = "*", features = ["backtrace"] }
color-backtrace = { version = "*", default-features = false, features = [
  "use-backtrace-crate",
] }
ctor = "0.4.2"
log = "0.4.17"
env_logger = "0.11.8"
