name: Fetaure Branch Build
run-name: Feature Branch Build

on:
  pull_request:
    branches:
      - main

jobs:
  main_branch:
    name: Feature Branch Build
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Seting up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Building
        run: |
          cargo build

      - name: Testing
        run: |
          cargo test
