name: Semantic Versioning
run-name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  semantise_the_shit:
    name: Main Branch Build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Semantic Dependencies
        run: |
          npm install npm
          npm install semantic-release
          npm install @semantic-release/changelog
          npm install @semantic-release/exec
          npm install @semantic-release/git
          npm install @semantic-release/github
          npm install asciidoctor-plantuml

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"

      - name: Debug Info Python tools
        run: |
          pip3 --version
          pip3 install --user bump2version

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          npx semantic-release

  create_doc:
    name: Create doc
    runs-on: ubuntu-latest
    needs: semantise_the_shit
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Building
        run: |
          cargo build

      - name: Clean doc folder
        run: |
          cargo clean --doc

      - name: Documentation
        run: |
          cargo doc --no-deps

      - name: Doc prep
        run: |
          echo '<meta http-equiv="refresh" content="0. url=./MathPotato/index.html">' > target/doc/index.html

      - name: Remove lock
        run: |
          rm target/doc/.lock

      - name: Building Manual
        run: |
          cargo install mdbook
          mdbook build docs

      - name: Copy Api to Manual
        run: |
          mkdir -p docs/book/api
          cp -r target/doc/* docs/book/api/

      - name: Setup pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: docs/book
